<Project>
    <PropertyGroup>
        <Authors>Microsoft</Authors>
        <Company>Microsoft</Company>
        <Description>Experimental, end-to-end AI features for .NET apps. Docs and info at https://github.com/dotnet-smartcomponents/smartcomponents</Description>
        <PackageTags>ai;aspnetcore;blazor;mvc;razor;autocomplete;paste;typeahead;smartcomponents;embedding;</PackageTags>
        <PackageProjectUrl>https://github.com/dotnet-smartcomponents/smartcomponents</PackageProjectUrl>

        <Version>0.1.7000</Version>
        <FileVersion>0.1.7000.0</FileVersion>
        <PackageOutputPath>$(MSBuildThisFileDirectory)artifacts\</PackageOutputPath>
        <IsPackable>false</IsPackable>
        <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
        <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
        <SharedSrcRoot>$(MSBuildThisFileDirectory)src\shared\</SharedSrcRoot>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
</Project>
